development:
    adapter: postgresql
    database: colibri_development
    username: postgres
    password: test0user
test:
    adapter: postgresql
    database: colibri_test
    username: postgres
    password: test0user
production:
    adapter: postgresql
    database: colibri_production
    username: colibri
    password: test0user
staging:
    adapter: postgresql
    database: colibri_staging
    username: colibri
    password: test0user
