development:
    adapter: postgresql
    database: online_bookings_development
    username: postgres
    password: test0user
test:
    adapter: postgresql
    database: online_bookings_test
    username: postgres
    password: test0user
production:
    adapter: postgresql
    database: online_bookings_production
    username: postgres
    password: test0user
