development:
    site_name: Colibri(DEV)
    site_domain: localhost.com
    site_protocol: 3000
    contact_email: cbonnet99@gmail.com
test:
    site_name: Colibri(TEST)
    site_domain: localhost
    contact_email: cbonnet99@gmail.com
production:
    site_name: Colibri
    site_domain: colibriapp.com
    contact_email: cbonnet99@gmail.com
staging:
    site_name: Colibri (STAGING)
    site_domain: staging.colibriapp.com
    contact_email: cbonnet99@gmail.com
