development:
    site_name: Colibri(DEV)
    site_host: localhost:3000
    contact_email: cbonnet99@gmail.com
test:
    site_name: Colibri(TEST)
    site_host: localhost
    contact_email: cbonnet99@gmail.com
production:
    site_name: Colibri
    site_host: bookings.beamazing.co.nz
    contact_email: cbonnet99@gmail.com
