development:
    site_name: Colibri(DEV)
    site_domain: localhost
    site_port: 3000
    contact_email: colibriapp@gmail.com
    from_email: colibriapp@gmail.com
test:
    site_name: Colibri(TEST)
    site_domain: localhost
    contact_email: colibriapp@gmail.com
    from_email: colibriapp@gmail.com
production:
    site_name: Colibri
    site_domain: colibriapp.com
    contact_email: colibriapp@gmail.com
    from_email: colibriapp@gmail.com
staging:
    site_name: Colibri (STAGING)
    site_domain: staging.colibriapp.com
    contact_email: colibriapp@gmail.com
    from_email: colibriapp@gmail.com
