#!/bin/sh
if [ ! -s "/tmp/GeoLiteCity.dat.gz" ] && [ ! -s "/tmp/GeoLiteCity.dat" ];
then
        echo 'Downloading GeoLite file'
        curl -g http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz > /tmp/GeoLiteCity.dat.gz
fi
if test ! -s "/tmp/GeoLiteCity.dat"
then
        echo 'Unzipping GeoLite file'
        gunzip -d -v /tmp/GeoLiteCity.dat.gz
fi
if test -s "$1"
then
        cp /tmp/GeoLiteCity.dat $1
else
        cp /tmp/GeoLiteCity.dat /var/rails/colibri_staging/current/geoip/
fi