#!/bin/sh
rm /tmp/GeoLiteCity.dat.gz
rm /tmp/GeoLiteCity.dat
curl -g -s http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz > /tmp/GeoLiteCity.dat.gz
ls -al /tmp
gunzip -d -v /tmp/GeoLiteCity.dat.gz
ls -al /tmp
if test -s "$1"
        mv /tmp/GeoLiteCity.dat /var/rails/$1/current/geoip/
then
        mv /tmp/GeoLiteCity.dat /var/rails/colibri_production/current/geoip/
fi